/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.nira.construction;

import org.junit.jupiter.api.Test;

class ConstructionReportGeneratorTest {
//    @Test void appHasAGreeting() {
//        ConstructionReportGenerator classUnderTest = new ConstructionReportGenerator();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
//    }
}
