/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.nira.construction;

import org.nira.construction.model.ConstructionInfo;
import org.nira.construction.service.data.DataReaderFactory;
import org.nira.construction.service.report.ReportProcessorService;
import org.nira.construction.service.report.impl.ReportProcessorServiceImpl;

import java.util.List;

public class ConstructionReportGenerator {

  public static void main(String[] args) {
    try {
      List<ConstructionInfo> constructionInfoList = DataReaderFactory.readFile("csv", "data.csv");
      ReportProcessorService reportProcessorService = new ReportProcessorServiceImpl();
      reportProcessorService.process("console", constructionInfoList);
    } catch (Exception e) {
      System.out.println("\"encountered error\", \"message\"=\"" + e.getMessage() + "\"");
    }
  }
}
